import { config } from '../config/env';

export interface MarketScheduleRequest {
  prompt: string;
  month: number;
  year: number;
  totalMembers: number;
  memberNames: string[];
  existingSchedule?: string[];
}

export interface MarketScheduleResponse {
  schedule: { date: string; member: string }[];
  explanation: string;
  confidence: number;
}

export class AIService {
  private static huggingFaceApiKey = config.huggingface?.apiKey;
  private static huggingFaceUrl = 'https://api-inference.huggingface.co/models';

  static async generateMarketSchedule(
    request: MarketScheduleRequest
  ): Promise<MarketScheduleResponse> {
    if (!this.huggingFaceApiKey) {
      throw new Error('Hugging Face API key not configured');
    }

    const { prompt, month, year, totalMembers, memberNames, existingSchedule } = request;

    // Create a comprehensive prompt for the AI
    const systemPrompt = `You are an AI assistant helping mess managers create fair and efficient market/rest day schedules.

Context:
- Month: ${month}/${year}
- Members: ${memberNames.join(', ')}
- Total members: ${totalMembers}
- Each member should get approximately equal number of rest days
- Rest days should be distributed fairly throughout the month
- Consider weekends and holidays for better scheduling
${existingSchedule ? `- Existing schedule: ${existingSchedule.join(', ')}` : ''}

User requirements: ${prompt}

Please provide:
1. A list of rest day assignments with member names and dates
2. A brief explanation of the schedule logic
3. Confidence score (0-100) of how well this meets the requirements

Format your response as JSON:
{
  "schedule": [{"date": "01/12/2024", "member": "John Doe"}, {"date": "02/12/2024", "member": "Jane Smith"}, ...],
  "explanation": "Brief explanation here",
  "confidence": 85
}`;

    try {
      const response = await fetch(`${this.huggingFaceUrl}/google/flan-t5-small`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${this.huggingFaceApiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          inputs: systemPrompt,
          parameters: {
            max_length: 1000,
            temperature: 0.7,
            do_sample: true,
          },
        }),
      });

      if (!response.ok) {
        if (response.status === 410) {
          // Model not available, use fallback
          throw new Error('AI_MODEL_UNAVAILABLE');
        }
        throw new Error(`Hugging Face API error: ${response.status}`);
      }

      const data = (await response.json()) as any;
      const generatedText = data[0]?.generated_text || '';

      // Try to parse the AI response as JSON
      try {
        const aiResponse = JSON.parse(generatedText);
        if (aiResponse.schedule && Array.isArray(aiResponse.schedule)) {
          return {
            schedule: aiResponse.schedule,
            explanation: aiResponse.explanation || 'Schedule generated by AI',
            confidence: aiResponse.confidence || 80,
          };
        }
      } catch (parseError) {
        // If parsing fails, extract JSON from text
        const jsonMatch = generatedText.match(/\{[\s\S]*\}/);
        if (jsonMatch) {
          try {
            const aiResponse = JSON.parse(jsonMatch[0]);
            if (aiResponse.schedule && Array.isArray(aiResponse.schedule)) {
              return {
                schedule: aiResponse.schedule,
                explanation: aiResponse.explanation || 'Schedule generated by AI',
                confidence: aiResponse.confidence || 80,
              };
            }
          } catch (e) {
            // Continue to fallback
          }
        }
      }
    } catch (error: any) {
      if (error.message === 'AI_MODEL_UNAVAILABLE') {
        // Use fallback mock schedule
      } else {
        throw error;
      }
    }

    // Fallback mock schedule
    const mockSchedule: { date: string; member: string }[] = [];
    const daysInMonth = new Date(year, month, 0).getDate();
    const restDaysPerMember = Math.floor(daysInMonth / totalMembers);

    const allDates: string[] = [];
    for (let day = 1; day <= daysInMonth; day++) {
      allDates.push(
        `${day.toString().padStart(2, '0')}/${month.toString().padStart(2, '0')}/${year}`
      );
    }

    for (let i = allDates.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [allDates[i], allDates[j]] = [allDates[j], allDates[i]];
    }

    let dateIndex = 0;
    for (let i = 0; i < totalMembers; i++) {
      const memberName = memberNames[i] || `Member ${i + 1}`;
      for (let j = 0; j < restDaysPerMember && dateIndex < allDates.length; j++) {
        mockSchedule.push({
          date: allDates[dateIndex],
          member: memberName,
        });
        dateIndex++;
      }
    }

    return {
      schedule: mockSchedule,
      explanation: `Generated schedule with ${restDaysPerMember} rest days per member (AI service temporarily unavailable)`,
      confidence: 75,
    };
  }

  static async generateMealPlan(prompt: string): Promise<string> {
    if (!this.huggingFaceApiKey) {
      throw new Error('Hugging Face API key not configured');
    }

    const systemPrompt = `You are a culinary assistant helping create meal plans for mess management.

User request: ${prompt}

Provide a detailed weekly meal plan with recipes, ingredients, and nutritional information. Structure it as a 7-day plan with breakfast, lunch, and dinner for each day. Include notes about dietary considerations if relevant.`;

    try {
      const response = await fetch(`${this.huggingFaceUrl}/google/flan-t5-small`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${this.huggingFaceApiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          inputs: systemPrompt,
          parameters: {
            max_length: 1500,
            temperature: 0.8,
            do_sample: true,
          },
        }),
      });

      if (!response.ok) {
        if (response.status === 410) {
          throw new Error('AI_MODEL_UNAVAILABLE');
        }
        throw new Error(`Hugging Face API error: ${response.status}`);
      }

      const data = (await response.json()) as any;
      return data[0]?.generated_text || 'Unable to generate meal plan from AI';
    } catch (error: any) {
      if (error.message === 'AI_MODEL_UNAVAILABLE') {
        // Return a prompt-based mock meal plan
        const lowerPrompt = prompt.toLowerCase();
        const isDiabetic =
          lowerPrompt.includes('diabetic') ||
          lowerPrompt.includes('diabetes') ||
          lowerPrompt.includes('low carb');
        const isVegetarian = lowerPrompt.includes('vegetarian') || lowerPrompt.includes('vegan');

        let mealPlan = `Generated Meal Plan Based on Request: "${prompt}"\n\n**Weekly Meal Plan for Mess Management**\n\n`;

        if (isDiabetic) {
          mealPlan += `**Diabetic-Friendly Meal Plan (Low Carb)**\n\n**Monday:** Breakfast: Eggs and avocado. Lunch: Grilled chicken salad. Dinner: Baked salmon with broccoli.\n**Tuesday:** Breakfast: Greek yogurt. Lunch: Turkey wraps. Dinner: Stir-fried tofu.\n**Wednesday:** Breakfast: Omelette. Lunch: Tuna salad. Dinner: Lean beef with vegetables.\n**Thursday:** Breakfast: Cottage cheese. Lunch: Egg salad. Dinner: Baked chicken.\n**Friday:** Breakfast: Smoothie. Lunch: Shrimp stir-fry. Dinner: Vegetable soup.\n**Saturday:** Breakfast: Chia pudding. Lunch: Grilled fish. Dinner: Turkey meatballs.\n**Sunday:** Breakfast: Avocado bowl. Lunch: Caesar salad. Dinner: Baked cod.\n\n*Note: Low-carb focus for diabetes management.*`;
        } else if (isVegetarian) {
          mealPlan += `**Vegetarian Meal Plan**\n\n**Monday:** Breakfast: Oatmeal. Lunch: Vegetable curry. Dinner: Lentil soup.\n**Tuesday:** Breakfast: Yogurt. Lunch: Paneer. Dinner: Vegetable biryani.\n**Wednesday:** Breakfast: Toast. Lunch: Chickpea salad. Dinner: Mushroom stir-fry.\n**Thursday:** Breakfast: Smoothie. Lunch: Pizza. Dinner: Tofu curry.\n**Friday:** Breakfast: Cereal. Lunch: Falafel. Dinner: Stuffed peppers.\n**Saturday:** Breakfast: Pancakes. Lunch: Quinoa salad. Dinner: Vegetable stew.\n**Sunday:** Breakfast: Waffles. Lunch: Salad. Dinner: Pasta.\n\n*Note: Plant-based meals.*`;
        } else {
          mealPlan += `**Standard Meal Plan**\n\n**Monday:** Breakfast: Oatmeal. Lunch: Chicken curry. Dinner: Stir-fry.\n**Tuesday:** Breakfast: Toast. Lunch: Lentil soup. Dinner: Fish.\n**Wednesday:** Breakfast: Yogurt. Lunch: Beef stew. Dinner: Pasta.\n**Thursday:** Breakfast: Pancakes. Lunch: Biryani. Dinner: Salad.\n**Friday:** Breakfast: Cereal. Lunch: Fish curry. Dinner: Curry.\n**Saturday:** Breakfast: Eggs. Lunch: Pizza. Dinner: Burgers.\n**Sunday:** Breakfast: Waffles. Lunch: Chicken. Dinner: Soup.\n\n*Note: Balanced nutrition.*`;
        }

        return mealPlan;
      }
      throw error;
    }
  }
}
